let snacklist = [
  "Oreo",
  "Chocolate Creme Oreo ",
  " Golden Oreo",
  " Strawberry Cheesecake Oreo",
  "Milk Chocolate Coated Oreo",
  "White Choc Coated Oreo",
  "Red Velvet Cream Oreo",
  "Birthday Cake Oreo",
  "Peanut Butter Oreo",
  "Mint Oreo",
  "Lemon Cream Oreo",
  " Chocolate Peanut Butter Pie Sandwich Oreo",
  "Carrot Cake Oreo",
  " Cookie Butter Creme Oreo ",
  "Cherry Cola Oreo",
  "Halloween Cookie Oreo",
  " Chocolate Creme Golden Oreo",
  "Kettle Corn Oreo",
  "Thins Bites Fudge Dipped Oreo",
  "Double Stuf Oreo",
  "Thins Bites White Fudge Dipped Oreo",
  "Thins Bites Fudge Dipped Mint Creme Oreo",
  "Thins Latte Creme Oreo",
  "Thins Bites Fudge Dipped Coconut Oreo",
  " Thins Pistachio Creme Oreo",
  "Marshmallow Moon Cookies Oreo",
  "S'mores Oreo",
  "Cookie Dough Oreo",
  "Golden Double Stuf Oreo",
  "Chocolate Creme Oreo",
  "Triple Double Oreo",
  "Peanut Butter Creme Double Stuf Oreo",
  "Peanut Butter Oreo",
  "Mini Oreo",
  "Mini Golden Oreo",
  "Triple Double Neapolitan Oreo",
  "Watermelon Oreo",
  "Strawberries N' Creme Oreo",
  "NASCAR Oreo",
  "Creamsicle Oreo",
  "Mega Stuf Oreo",
  "De Todito Paketón Sabor Mix",
  "Doritos Bits Zero's Texas Paprika",
  "Doritos Black Pepper Jack Tortilla Chips",
  "Doritos Blaze",
  "Doritos Blazin' Buffalo & Ranch Tortilla Chips",
  "Doritos Blue Grilled Steak",
  "Doritos Burn",
  "Doritos Chilli Heatwave",
  "Doritos Collisions Blaze Ultimate Cheddar",
  "Doritos Cooler Ranch",
  "Doritos Dinamita Mojo Criollo",
  "Doritos Dinamita Nacho Picoso",
  "Doritos Edge Nacho Cheesier (low carb)",
  "Doritos Extreme Kickin' Chili",
  "Doritos Extreme Queso Grande",
  "Doritos Extreme Zesty Sour Cream & Cheddar",
  "Doritos Fiery Fusion",
  "Doritos Fiery Habanero",
  "Doritos Flamas",
  "Doritos Flamin' Hot Cool Ranch new",
  "Doritos Flamin' Hot Limón",
  "Doritos Flamin' Hot Nacho",
  "Doritos Guacamole!",
  "Doritos Heat Wave Barbecue",
  "Doritos Heat Wave Chipotle Cream",
  "Doritos Honey Chili",
  "Doritos Hot Corn",
  "Doritos Mexicana",
  "Doritos Mild Salt",
  "Doritos Mix Taco Explosion",
  "Doritos Mr. Dragon's Fire Chips",
  "Doritos Nacho Cheese",
  "Doritos Nacho Cheesier",
  "Doritos Original Taco",
  "Doritos Pepper Bacon",
  "Doritos Pizza Supreme",
  "Doritos Pizza-La Curry Monterey",
  "Doritos Pizzerola",
  "Doritos Poppin' Jalapeno",
  "Doritos Queijo Nacho",
  "Doritos Salsa!",
  "Doritos Screamin' Sriracha",
  "Doritos Seasoned Chicken",
  "Doritos Sizzlin' Picante",
  "Doritos Sonic Sour Cream",
  "Doritos Sour Cream & Onion",
  "Doritos Spicy Nacho",
  "Doritos Spicy Sweet Chili Tortilla Chips",
  "Doritos Spirals Sweet Barbecue",
  "Doritos Stax Mexican Chilli Salsa",
  "Doritos Ultimate Cheddar",
  "Doritos Wasabi",
  "Doritos Wild White Nacho Tortilla Chips",
  "Doritos Cool Ranch",
  "Doritos Nacho Cheese ",
  "Lay's Classic Flavor",
  "Lay's Barbecue",
  "Lay's BBQ Rib",
  "Lay's Beef",
  "Lay's California Coxol Dill",
  "Lay's Cheddar Jalapeño",
  "Lay's Cheese & Onion Potato Chips",
  "Lay's Cheesy Garlic Bread",
  "Lay's Chicken",
  "Lay's Chinese Szechuan Chicken",
  "Lay's Chipotle Ranch",
  "Lay's Classic Potato Chips",
  "Lay's Cool Guacamole",
  "Lay's Pure Tomato Flavor",
  "Lay's Roast Pork BBQ",
  "Lay's Roasted Chicxken Wing Flavor",
  "Lay's Salt & Vinegar Potato Chips",
  "Lay's Sea Salt & Black Pepper Flavor",
  "Lay's Smokey Bacon Potato Chips",
  "Lay's Sour Cream & Onion",
  "Lay's Spicy Ketchup",
  "Lay's Sriracha",
  "Lay's Sweet & Spicy Teriyaki",
  "Lay's Sweet Onion",
  "Lay's Swiss Cheese",
  "Lay's Texas Grilled BBQ Flavor",
  "Lay's Tomato French Fries",
  "Lay's Turkey Potato Chips",
  "Lay's Wasabi Flavor",
  "Lay's Wavy Bacon Wrapped Jalapeño Popper",
  "Lay's Wavy Cheddar",
  "Lay's Wavy Mango Salsa",
  "Lay's Wavy Ranch",
  "Lay's Sour Cream and Cheddar",
  "Natural Lay's Sea Salt & Vinegar Kettle Cooked Potato Chips",
  "Wavy Lay's Original Potato Chips",
  "Gushers",
  "Fruit by the foot",
  "Fruit roll up",
  "Fruit Snacks",
  "Skittles",
  "Gummy Bears",
  "Jolly Ranchers",
  "Sour Patch Kids",
  "M&M's",
  "Snickers",
  "Milky Way",
  "Twix",
  "Hershey Kiss",
  "Life Savers",
  "Nerds",
  "Nerds Rope",
  "Nerds Gummy Clusters",
  "Chocolate chip Cookies",
  "Chips Ahoy",
  "M&M Cookies",
  "Coca Cola",
  "Fanta",
  "Mountain Dew",
  "Dr Pepper",
  "Siera Mist",
  "Ginger Ale",
  "Butter Beer",
  "Pepsi",
  "Cherry Pepsi",
  "Root Bear",
  "Vanlla Ice Cream",
  "Chocolate Ice Cream",
  "Caramel Ice Cream",
  "Mint Chocolate Cip Ice Cream",
  "Mango Ice Cream",
  "Strawberry Ice Cream",
  "Mango",
  "Strawberry",
  "Blueberry",
  "Apple",
  "Peach",
  "Appricote",
  "Plum",
  "Banana",
  "Honey Dew",
  "Watermelon",
  "Carrots",
  "Corn",
];

let button = document.querySelector("#snacks");

button.addEventListener("click", (event) => {
  let snackidea = document.querySelector(".content p");
  let min = Math.ceil(0);
  let max = Math.floor(snacklist.length - 1);
  let snackIndex = Math.floor(Math.random() * (max - min + 1) + min);

  snackidea.textContent = snacklist[snackIndex];

  snackidea.classList.remove("hidden");
});

let snacksformbutton = document.querySelector("#snacksform");

snacksformbutton.addEventListener("click", (event) => {
  let snacksform = document.querySelector(".snackideaform form");
  snacksform.classList.remove("hidden");
});
